#!/bin/bash

# ----------------------------------------------------------------------
# ForkMasonMM			::	fork Debian Security archive
# Copyright				::	(C) 2011-2012 by the Cybernux Linux® DevTeam.
# Cybernux Linux® WWW	::	http://www.cybernux.org/
# Cybernux Linux® Dev	::	http://dev.cybernux.org/
# SVN Archive			::	http://svn.berlios.de/wsvn/forkmason-sec
# ----------------------------------------------------------------------
# Based on:
# The gNewSense Builder - http://gnewsense.org/Builder (GPLv2)
# ----------------------------------------------------------------------
# LICENSE:
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------


# --------------
# Get dist info
# -------------
. conf

# ----------------
# Set Destination
# ----------------
mkdir -pv $REPO_DEST/conf


cd $REPO_DEST

cat >  conf/distributions <<EOF
Origin: $DIST_NAME
Label: $DIST_NAME
Codename: $RELEASE-securiy
Update: Upstream
Architectures: $REPO_ARCHES source
Components: main community bound
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz
EOF

cat >  conf/updates <<EOF
Name: Upstream
Method: $SEC_MIRROR
Suite: $SEC_MIRROR_DIST
Components: main>main contrib>community non-free>bound
EOF
fi;



mkdir -p $REPO_DEST/apt/{var,lists/partial,cache/archives/partial}
touch $REPO_DEST/apt/status
touch conf/purge-$MIRROR_DIST


